Team/urls.py
# clubs urls.py
from django.conf.urls import patterns, include, url
from . import views


# TODO: I want to standardize namespace names to all lowercase
# e.g. confirmAskJoin > confirmaskjoin,
#      editMember > editMember
# TODO: addMembers is plural. singularize it
# were we really going to add members en masse?


urlpatterns = [
    url(
        regex=r"^$",
        view=views.TeamListView.as_view(),
        name="list"
    ),
    url(
        regex=r"^new$",
        view=views.TeamCreateView.as_view(),
        name="new"
    ),
    url(
        regex=r"^(?P<pk>\d+)$",
        view=views.TeamDetailView.as_view(),
        name="detail"
    ),
    url(
        regex=r"^join/(?P<pk>\d+)$",
        view=views.TeamAskJoinView.as_view(),
        name="askjoin"
    ),
    url(
        regex=r"^confirm/(?P<pk>\d+)$",
        view=views.TeamConfirmAskJoinView.as_view(),
        name="confirmAskJoin"
    ),
    url(
        regex=r"^deleterequest/(?P<pk>\d+)$",
        view=views.DeletePlayerRequest, 
        name="deleterequest"
        ),
    url(
        regex=r"^deleteplayer/(?P<team>\d+)/(?P<player>\d+)$",
        view=views.DeleteTeamPlayer, 
        name="deleteplayer"
    ),

   url(
        regex=r"^addplayer/(?P<pk>\d+)$",
        view=views.TeamAddPlayerView.as_view(),
        name="addplayer"
    ),

    # url(
    #     regex=r"^removeplayer/(?P<pk>\d+)$",
    #     view=views.TeamRemovePlayerView.as_view(),
    #     name="removeplayer"
    # ),
   # url(
   #      regex=r"^editmember/(?P<pk>\d+)$",
   #      view=views.ClubEditMemberView.as_view(),
   #      name="editMember"
   #  ),
    url(
        regex=r"^results/(?P<pk>\d+)$",
        view=views.TeamResultsView.as_view(),
        name="result"
    ),
    # url(
    #     regex=r"^update/(?P<pk>\d+)$",
    #     view=views.ClubUpdateView.as_view(),
    #     name="update"
    # ),
    # url(
    #     regex=r"^delete/(?P<pk>\d+)$",
    #     view=views.ClubDeleteView.as_view(),
    #     name="delete"
    # ),
    # added by Daniel Henderson
    # call this url with the PK of a PlayerRequest object
    url(r'^compare/(?P<playerRequest>\d+)$', views.compareRequestedPlayers, name='compare'),
]

mysite/urls.py
from django.conf.urls import patterns, include, url

# from . import views
from login.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', welcome),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', logout_page),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
                       url(r'^register/$', register),
                       url(r'^register/success/$', register_success),
                       url(r'^home/$', home),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^player/', include('Players.urls', namespace='Players')),
                       url(r'^search/$', search),
                       url(r'^team/', include('Team.urls', namespace='Team')),
                       # url(r'^players/', include('clubMembers.urls', namespace='members')),
                       # url(r'^team/', include('Team.urls', namespace="Team")),
                       )
                       

Players/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.forms import ModelForm

# from nflstats.models import CsvModel

"""
This model will provide additional custom fields to the built-in
User class that django provided.

We need to store at least a phone number.
"""
class Player(models.Model):
    name = models.CharField(max_length = 100)
    pos = models.CharField(max_length = 5)
    fpts = models.FloatField()
    fptsg= models.FloatField()
    gp= models.FloatField()
    pyds = models.FloatField()
    ptd = models.FloatField()
    ryd = models.FloatField()
    rtd = models.FloatField()
    recyds = models.FloatField()
    rectd = models.FloatField()
    fum = models.FloatField()
    sack = models.FloatField()
    fr = models.FloatField()
    intercept = models.FloatField()
    td = models.FloatField()
    sfty = models.FloatField()
    fg = models.FloatField()
    fgmiss = models.FloatField()
    xpt = models.FloatField()

    # def __unicode__(self):
    #     return self.shortDescription









# class ClubMember(models.Model):
#     member = models.OneToOneField(User, primary_key=True)
#     # phone = models.CharField(max_length=12)
#     # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
#     phone_regex_us_easy = RegexValidator(regex=r'^\(\d{3}\)[ -]\d{3}[ -]\d{4}', message="Phone must be (###) 555 1212 or ### 555 1212; you can use dashes instead of spaces")
#     phone_number = models.CharField(max_length=20, validators=[phone_regex_us_easy], blank=False) # validators should be a list
#     zip_regex = RegexValidator(regex=r'^\d{5}$', message="5-digit Zip Code only")
#     member_zip = models.CharField(max_length=5, validators=[zip_regex], blank=False)
#     # we can add a photo or avatar image later
#     # TODO: what additional info about members do we want?

#     def create_member(self, phone_number, member, **extra_fields):
#         return self._create_member(phone_number, member, **extra_fields)

#     def requester_relationship(self, asking_member):
#         """
#         The asking_member will be the person him/herself,
#         or will be in the same club,
#         or will be in a club the person wants to join
#         or will be world+dog member.
#         Return a string of the relationship
#         :param asking_member:
#         :return:
#         """
#         if asking_member == self:
#             # the person himself
#             return "self_request"

#         ask_user = asking_member.member
#         self_user = self.member
#         asker_clubs = Club.objects.filter(members=ask_user)
#         self_clubs = Club.objects.filter(members=self_user)
#         common_clubs = asker_clubs & self_clubs
#         print("common clubs:")
#         for c in common_clubs:
#             print(c.name)
#         if len(common_clubs) > 0:
#             return "club_buddy"
#         # TODO: look up all club requests, get a queryset of those clubs
#         # compare to requester's clubs
#         # c_reqs = Club.objects.filter(members__requester=self_user)
#         # # club_requests = MemberRequest.objects.filter(requester=self_user)
#         #
#         # # requested_clubs = club_requests.all(self_clubs)
#         # common_clubs = asker_clubs & c_reqs
#         # print("request common clubs")
#         # for c in common_clubs:
#         #     print(c.name)
#         # if len(common_clubs) > 0:
#         #     return "prospective_club_buddy"
#         return "world_dog"

#     def get_prospective_buddy_info(self):
#         info = {"username":self.member.username}
#         return info







# class MemberRating(models.Model):
#     target_member = models.OneToOneField(User)
#     rated_by = models.ForeignKey(User, related_name="member_related", null=False, blank=False)
#     rating = models.PositiveSmallIntegerField()
#     rating_date = models.DateField()

Team/views.py
# clubs/views.py
from Team.models import PlayerRequest
from .models import Team, PlayerRequest
from Players.models import Player
from django.contrib.auth.models import User

# for I18N
from django.utils.translation import ugettext as _

# TSoD page 98, Class-based views
from django.core.urlresolvers import reverse
# end TSoD
# signals.receiver
from django.db.models import signals

from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from braces.views import LoginRequiredMixin
from django.contrib import messages

from Team.forms.team_forms import NewTeamForm
from Team.forms.player_form import newPlayerForm
from Team.forms.playerrequestform import newPlayerRequest

# from Team.forms.member_form import newMemberForm
from helpers.navbar_helpers import NavBarMixin
from django.contrib import messages
import copy

class TeamActionMixin(object):
    
    fields = ('name')
    
    @property
    def success_msg(self):
        return NotImplemented

    @staticmethod
    def is_member_current_user(self, member):
        """
        Is the current user the member being looked at
        :param self:
        :return:
        """
        pass
        

class TeamListView(LoginRequiredMixin, TeamActionMixin, NavBarMixin, ListView):
    model = Team
    page_title = _("Team List")
    def get_context_data(self, **kwargs):
        context = super(TeamListView, self).get_context_data(**kwargs)
        this_owner = self.request.user
        teams = Team.objects.filter(owner=this_owner)
        context["team_list"] = teams

        return context



class TeamDetailView(LoginRequiredMixin, TeamActionMixin, NavBarMixin, DetailView):
    model = Team
    page_title = _("Team Detail")

    def get_context_data(self, **kwargs):
        this_team = self.get_object(queryset=None)
        if Team.is_owner(this_team, self.request.user):
            context = super(TeamDetailView, self).get_context_data(**kwargs)
            player_list = this_team.players.all()
            player_requests = PlayerRequest.objects.filter(teamToJoin=this_team)

            fpts = 0
            fptsg = 0
            gp = 0
            pyds = 0
            ptd = 0
            ryd = 0
            rtd = 0
            recyds = 0
            rectd = 0
            fum = 0
            sack = 0
            fr = 0
            intercept = 0
            td = 0
            sfty =0
            fg = 0
            fgmiss = 0
            xpt = 0
            dfpts = 0
            dfptsg = 0
            dgp = 0
            dpyds = 0
            dptd = 0
            dryd = 0
            drtd = 0
            drecyds = 0
            drectd = 0
            dfum = 0
            dsack = 0
            dfr = 0
            dintercept = 0
            dtd = 0
            dsfty =0
            dfg = 0
            dfgmiss = 0
            dxpt = 0

            context["player_request_count"] = len(player_requests)
            context["player_actual_count"] = len(player_list)
            context["player_list"] = player_list
            context["player_request_list"] = player_requests
            if(player_list != None):
                for p in player_list:
                    fpts += p.fpts
                    fptsg += p.fptsg
                    gp += p.gp
                    pyds += p.pyds
                    ptd += p.ptd
                    ryd += p.ryd
                    rtd += p.rtd
                    recyds += p.recyds
                    rectd += p.rectd
                    fum += p.fum
                    sack += p.sack
                    fr += p.fr
                    intercept += p.intercept
                    td += p.td
                    sfty += p.sfty
                    fg += p.fg
                    fgmiss += p.fgmiss
                    xpt += p.xpt
            if(len(player_requests) > 1):
                dfpts = player_requests[0].player.fpts - player_requests[1].player.fpts
                dfptsg = player_requests[0].player.fptsg - player_requests[1].player.fptsg
                dgp = player_requests[0].player.gp - player_requests[1].player.gp
                dpyds = player_requests[0].player.pyds - player_requests[1].player.pyds
                dptd = player_requests[0].player.ptd - player_requests[1].player.ptd
                dryd = player_requests[0].player.ryd - player_requests[1].player.ryd
                drtd = player_requests[0].player.rtd - player_requests[1].player.rtd
                drecyds = player_requests[0].player.recyds - player_requests[1].player.recyds
                drectd = player_requests[0].player.rectd - player_requests[1].player.rectd
                dfum = player_requests[0].player.fum - player_requests[1].player.fum
                dsack = player_requests[0].player.sack - player_requests[1].player.sack
                dfr = player_requests[0].player.fr - player_requests[1].player.fr
                dintercept = player_requests[0].player.intercept - player_requests[1].player.intercept
                dtd = player_requests[0].player.td - player_requests[1].player.td
                dsfty = player_requests[0].player.sfty - player_requests[1].player.sfty
                dfg = player_requests[0].player.fg - player_requests[1].player.fg
                dfgmiss = player_requests[0].player.fgmiss - player_requests[1].player.fgmiss
                dxpt = player_requests[0].player.xpt - player_requests[1].player.xpt


            for p in player_list:
                fpts += p.fpts
                fptsg += p.fptsg
                gp += p.gp
                pyds += p.pyds
                ptd += p.ptd
                ryd += p.ryd
                rtd += p.rtd
                recyds += p.recyds
                rectd += p.rectd
                fum += p.fum
                sack += p.sack
                fr += p.fr
                intercept += p.intercept
                td += p.td
                sfty += p.sfty
                fg += p.fg
                fgmiss += p.fgmiss
                xpt += p.xpt


            count = 0;

            acomp = PlayerRequest.objects.filter(teamToJoin=this_team)
            qcomp = []

            for p in acomp:
                for s in acomp:
                    if p.player.pk!=s.player.pk:
                        comp=copy.deepcopy(acomp[0])
                        comp.player.pk = p.player.pk
                        comp.player.name = p.player.name + " vs " + s.player.name
                        comp.player.fpts = p.player.fpts - s.player.fpts
                        comp.player.fptsg = p.player.fptsg - s.player.fptsg
                        comp.player.gp = p.player.gp - s.player.gp
                        comp.player.pyds = p.player.pyds - s.player.pyds
                        comp.player.ptd = p.player.ptd - s.player.ptd
                        comp.player.ryd = p.player.ryd - s.player.ryd
                        comp.player.rtd = p.player.rtd - s.player.rtd
                        comp.player.recyds = p.player.recyds - s.player.recyds
                        comp.player.rectd = p.player.rectd - s.player.rectd
                        comp.player.fum = p.player.fum - s.player.fum
                        comp.player.sack = p.player.sack - s.player.sack
                        comp.player.fr = p.player.fr - s.player.fr
                        comp.player.intercept = p.player.intercept - s.player.intercept
                        comp.player.td = p.player.td - s.player.td
                        comp.player.sfty = p.player.sfty - s.player.sfty
                        comp.player.fg = p.player.fg - s.player.fg
                        comp.player.fgmiss = p.player.fgmiss - s.player.fgmiss
                        comp.player.xpt = p.player.xpt - s.player.xpt
                        qcomp.append(comp)
                        count = count + 1

    #                  returns list of comparisons 1v2 1v3...1vn 2v3 2v4...2vn
            context["comparison_list"]= qcomp
            context["fpts"] = fpts
            context["fptsg"] = fptsg
            context["gp"] = gp
            context["pyds"] = pyds
            context["ptd"] = ptd
            context["ryd"] = ryd
            context["rtd"] = rtd
            context["recyds"] = recyds
            context["rectd"] = rectd
            context["fum"] = fum
            context["sack"] = sack
            context["fr"] = fr
            context["intercept"] = intercept
            context["td"] = td
            context["sfty"] = sfty
            context["fg"] = fg
            context["fgmiss"] = fgmiss
            context["xpt"] = xpt

            context["dfpts"] = dfpts
            context["dfptsg"] = dfptsg
            context["dgp"] = dgp
            context["dpyds"] = dpyds
            context["dptd"] = dptd
            context["dryd"] = dryd
            context["drtd"] = drtd
            context["drecyds"] = drecyds
            context["drectd"] = drectd
            context["dfum"] = dfum
            context["dsack"] = dsack
            context["dfr"] = dfr
            context["dintercept"] = dintercept
            context["dtd"] = dtd
            context["dsfty"] = dsfty
            context["dfg"] = dfg
            context["dfgmiss"] = dfgmiss
            context["dxpt"] = dxpt
        # all_entries = Team.players.all()
        # context["top_panel_name"] = "Members"
        # context["bottom_panel_name"] = "Request Membership"
        # context["member_count"] = len(player_list)
        # if Team.is_owner(this_team, self.request.user):
        #     # member specific context data goes here
        #     context["bottom_panel_name"] = "Membership Requests"
        # context["player"] = True


        #     context["member_requests"] = this_team.player_requests_list()
        #     if Team.is_owner(this_team, self.request.user):
        #         context["owner"] = True

        # if Team.is_owner(this_team, self.request.user):

templates/Team/comparePlayers.html
{% extends "base_leftSidebar.html" %}
{% block content %}
<h3> Comparing stats with {{ player.player.name }}
<table>
<tr>
<td>Name</td>
<td>Position</td>
<td>Running Yards</td>
<td>Sack</td>
</tr>
    {% for o in others %}
    <tr>
    <td>{{ o.player.name }}</td>
    <td>{{ o.player.pos }}</td>
    <td {% if o.ryd > player.player.ryd %}bgcolor="#FF0000"{% else %}bgcolor="#00FF00"{% endif %}>{{ o.player.ryd }}</td>
    <!--This will alternately color the table cell red if other player's ryd stat is greater than player.ryd stat-->
    <!--or green otherwise. Tweak the colors as needed. I don't know if ryd is better when larger.-->
    <td>{{ o.player.sack|floatformat:2 }}</td>
    <!-- see https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#floatformat for other ways to format floats -->
    </tr>
    {% endfor %}
</table>
{% endblock %}
{% block sidebar %}
{#    TODO: make this look better, think up more content to put here. #}
    Put list of your clubs<br/>
<a href="{% url 'Team:new' %}">Create Your Own Club</a>
{% endblock %}

templates/Team/pending_team_list_partial.html
<!-- <ul style="list-style: none;">
    {%  for req in member_requests %}
        <li><a href="{% url 'members:detail' pk=req.requester.pk %}">{{ req.requester.username }}</a> wants to join your club. </li>
        <li>Message: "{{ req.reasonMessage }}"</li>
        {% if leader %}
        <li><a href="{% url 'clubs:addmember' pk=req.pk %}" class="btn btn-lg btn-primary btn-block" >Accept</a></li>
        <li><a href="{% url 'clubs:declinemember' pk=req.pk %}" class="btn btn-lg btn-danger btn-block">Decline</a></li>
        {% elif member %}
        <li>Let your club leader know what you think</li>

        {% else %}
        You shouldn't be seeing this info, since you're not in the club
        {% endif %}
    {% endfor %}
</ul>
 -->

templates/Team/playerrequest_detail.html
{% extends "base.html" %} -->

<div class="container">
    <div class="row">
    {% block title %}Welcome Back{% endblock %}
    {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %}
    {% block content %}
    <div class="col-md-4"></div>
    <div class="container col-md-4">
        <h3>Success!</h3>
        You have added {{ object.player.name }},
        to the team {{ object.teamToJoin.name }}
        for user {{ object.requester.username }}.
          <!-- <input href="Team:confirmAskJoin" type="submit" value="Save" /> -->

      </div>
            <div class="col-md-4"></div>

    {% endblock %}
    </div>
 </div>

templates/Team/playerrequest_form.html
{% extends "base.html" %} -->

<div class="container">
    <div class="row">
    {% block title %}Welcome Back{% endblock %}
    {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %}
    {% block content %}
    <div class="col-md-4"></div>
    <div class="container col-md-4">
        <h3>This is the Team data entry form</h3>
        
        <form action="" class="form" method="POST">
          {% csrf_token %}
          <ul>
            {{ form.as_ul }}
          </ul>
          <input id="save_team" type="submit" value="Save" />
        </form>
      </div>
            <div class="col-md-4"></div>

    {% endblock %}
    </div>
 </div>

templates/Team/team_and_policy_form.html
{% extends base_leftSidebar.html %}
This is the form for creating club and club policy.

templates/Team/team_detail.html
{% extends "base.html" %}
{% block content %}
<!-- <div class="col-md-2"></div> -->
<div class="container col-md-4">

    <h5><b>Team Name: </b>{{ team.name }}</h5>
    <h5><b>Team Leader: </b> {{ team.owner }}</h5>
    {{ object.player.name }}

                List of Team's members
               <h5>{{ player_actual_count }} player{{ player_actual_count|pluralize }} in this team</h5>
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Name  &nbsp;</b> </td>
    <td <b>Pos  &nbsp;</b></td>
    <td <b>Fantasy Pts  &nbsp;</b></td>
    <td <b>Fantasy PPG  &nbsp;</b> </td>
    <td <b>Games Played  &nbsp;</b></td>
    <td <b>Pass Yds  &nbsp;</b> </td>
    <td <b>Pass TDs  &nbsp;</b> </td>
    <td <b>Rush Yds  &nbsp;</b> </td>
    <td <b>Rush TDs  &nbsp;</b> </td>
    <td <b>Rec Yds  &nbsp;</b> </td>
    <td <b>Rec TDs  &nbsp;</b> </td>
    <td <b>Fum Lost  &nbsp;</b> </td>
    <td <b>Sacks  &nbsp;</b> </td>
    <td <b>Fum Rec  &nbsp;</b> </td>
    <td <b>Ints  &nbsp;</b> </td>
    <td <b>Def TDs  &nbsp;</b> </td>
    <td <b>Safety  &nbsp;</b></td>
    <td <b>FG  &nbsp;</b> </td>
    <td <b>FG Miss  &nbsp;</b> </td>
    <td <b>Ex Pts  &nbsp;</b> </td>
  </tr>
{% for p in player_list %}
<tr>
    <td style="white-space:nowrap;">{{ p.name }} &nbsp;</td>
    <td>{{ p.pos }}</td>
    <td>{{ p.fpts }}</td>
    <td>{{ p.fptsg }}</td>
    <td>{{ p.gp }}</td>
    <td>{{ p.pyds }}</td>
    <td>{{ p.ptd }}</td>
    <td>{{ p.ryd }}</td>
    <td>{{ p.rtd }}</td>
    <td>{{ p.recyds }}</td>
    <td>{{ p.rectd }}</td>
    <td>{{ p.fum }}</td>
    <td>{{ p.sack }}</td>
    <td>{{ p.fr }}</td>
    <td>{{ p.intercept }}</td>
    <td>{{ p.td }}</td>
    <td>{{ p.sfty }}</td>
    <td>{{ p.fg }}</td>
    <td>{{ p.fgmiss }}</td>
    <td>{{ p.xpt }}</td>
    <td><center><a href="/team/deleteplayer/{{team.pk}}/{{p.pk}}" class="btn btn-primary btn-block">Remove from Team</a></center><td>
  </tr>
{% endfor %}
    <td>Total</td>
    <td></td>
    <td>{{ fpts }}</td>
    <td>{{ fptsg }}</td>
    <td>{{ gp }}</td>
    <td>{{ pyds }} </td>
    <td>{{ ptd }}</td>
    <td>{{ ryd }}</td>
    <td>{{ rtd }}</td>
    <td>{{ recyds }}</td>
    <td>{{ rectd }}</td>
    <td>{{ fum }}</td>
    <td>{{ sack }}</td>
    <td>{{ fr }}</td>
    <td>{{ intercept }}</td>
    <td>{{ td }}</td>
    <td>{{ sfty }}</td>
    <td>{{ fg }}</td>
    <td>{{ fgmiss }}</td>
    <td>{{ xpt }}</td>
</table> 

<h5>{{ player_request_count }} player in queue for this team</h5>
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Name  &nbsp;</b> </td>
    <td <b>Pos  &nbsp;</b></td>
    <td <b>Fantasy Pts  &nbsp;</b></td>
    <td <b>Fantasy PPG  &nbsp;</b> </td>
    <td <b>Games Played  &nbsp;</b></td>
    <td <b>Pass Yds  &nbsp;</b> </td>
    <td <b>Pass TDs  &nbsp;</b> </td>
    <td <b>Rush Yds  &nbsp;</b> </td>
    <td <b>Rush TDs  &nbsp;</b> </td>
    <td <b>Rec Yds  &nbsp;</b> </td>
    <td <b>Rec TDs  &nbsp;</b> </td>
    <td <b>Fum Lost  &nbsp;</b> </td>
    <td <b>Sacks  &nbsp;</b> </td>
    <td <b>Fum Rec  &nbsp;</b> </td>
    <td <b>Ints  &nbsp;</b> </td>
    <td <b>Def TDs  &nbsp;</b> </td>
    <td <b>Safety  &nbsp;</b></td>
    <td <b>FG  &nbsp;</b> </td>
    <td <b>FG Miss  &nbsp;</b> </td>
    <td <b>Ex Pts  &nbsp;</b> </td>
  </tr>

{% for p in player_request_list %}

    <td style="white-space:nowrap;">{{ p.player.name }} &nbsp;</td>
    <td>{{ p.player.pos }}</td>
    <td>{{ p.player.fpts }}</td>
    <td>{{ p.player.fptsg }}</td>
    <td>{{ p.player.gp }}</td>
    <td>{{ p.player.pyds }}</td>
    <td>{{ p.player.ptd }}</td>
    <td>{{ p.player.ryd }}</td>
    <td>{{ p.player.rtd }}</td>
    <td>{{ p.player.recyds }}</td>
    <td>{{ p.player.rectd }}</td>
    <td>{{ p.player.fum }}</td>
    <td>{{ p.player.sack }}</td>
    <td>{{ p.player.fr }}</td>
    <td>{{ p.player.intercept }}</td>
    <td>{{ p.player.td }}</td>
    <td>{{ p.player.sfty }}</td>
    <td>{{ p.player.fg }}</td>
    <td>{{ p.player.fgmiss }}</td>
    <td>{{ p.player.xpt }}</td>
    <td><center><a href="{% url 'Team:addplayer' p.pk %}" class="btn btn-primary btn-block">Add to Team</a></center><td>
    <td><center><a href="{% url 'Team:deleterequest' p.pk %}" class="btn btn-primary btn-block">Remove from Queue</a></center><td>
  </tr>
{% for s in comparison_list %}


    {% if p.player.pk == s.player.pk %}
      <td style="white-space:nowrap;">{{ s.player.name }} &nbsp;</td>
    <td>{{ s.player.pos }}</td>
    <td>{{ s.player.fpts }}</td>
    <td>{{ s.player.fptsg }}</td>
    <td>{{ s.player.gp }}</td>
    <td>{{ s.player.pyds }}</td>
    <td>{{ s.player.ptd }}</td>
    <td>{{ s.player.ryd }}</td>
    <td>{{ s.player.rtd }}</td>
    <td>{{ s.player.recyds }}</td>
    <td>{{ s.player.rectd }}</td>
    <td>{{ s.player.fum }}</td>
    <td>{{ s.player.sack }}</td>
    <td>{{ s.player.fr }}</td>
    <td>{{ s.player.intercept }}</td>
    <td>{{ s.player.td }}</td>
    <td>{{ s.player.sfty }}</td>
    <td>{{ s.player.fg }}</td>
    <td>{{ s.player.fgmiss }}</td>
    <td>{{ s.player.xpt }}</td>
  </tr>
{% endif %}
{%  endfor %}
{% endfor %}

</table> 
    <br />
</div>
<div class="container col-md-4"></div>



{% endblock %}

    

templates/Team/team_form.html
{% extends "base.html" %} -->

<div class="container">
    <div class="row">
    {% block title %}Welcome Back{% endblock %}
    {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %}
    {% block content %}
    <div class="col-md-4"></div>
    <div class="container col-md-4">
        <h3>This is the Team data entry form</h3>
        
        <form action="" class="form" method="POST">
          {% csrf_token %}
          <ul>
            {{ form.as_ul }}
          </ul>
          <input id="save_team" type="submit" value="Save" />
        </form>
      </div>
            <div class="col-md-4"></div>

    {% endblock %}
    </div>
 </div>

templates/Team/team_list.html
{% extends "base_leftSidebar.html" %}
{% block content %}
    {% for team in team_list %}
        <div class="col-sm-4 col-lg-4 col-md-4">
            <!-- <div class="thumbnail"> -->
                <h4><a href="{% url 'Team:detail' team.pk %}">{{ team.name }}</a></h4>
        </div>
    {% endfor %}
{% endblock %}
{% block sidebar %}
{#    TODO: make this look better, think up more content to put here. #}
    Teams:<br/>
<a href="{% url 'Team:new' %}">Create Your Own Team</a>
{% endblock %}