Players/urls.py
from django.conf.urls import patterns, include, url
from . import views


urlpatterns = [
	url(
        regex=r"^(?P<pk>\d+)$",
        view=views.PlayerDetailView.as_view(),
        name="detail"
        ),
	url(
		regex=r"^(?P<pk>\d+)$",
        view=views.PlayerDetailView.as_view(),
        name="mydetail"
        ),
    url(
        regex=r"^(?P<pk>\d+)$",
        view=views.PlayerDetailView.as_view(),
        name="detail"
        ),
    ]

# urlpatterns = [
#     url(
#         regex=r"^$",
#         view=views.ClubMemberListView.as_view(),
#         name="list"
#     ),
#     url(
#         regex=r"^(?P<pk>\d+)$",
#         view=views.ClubMemberDetailView.as_view(),
#         name="detail"
#     ),
#     url(
#         regex=r"info/^(?P<pk>\d+)$",
#         view=views.ClubMemberInfoView.as_view(),
#         name="info"
#     ),
#     url(
#         regex=r"^welcome/(?P<pk>\d+)$",
#         view=views.ClubMemberFirstTimeView.as_view(),
#         name="first_time"
#     ),
#     url(
#         regex=r"^results/(?P<pk>\d+)$",
#         view=views.ClubMemberResultsView.as_view(),
#         name="results"
#     ),
#     url(
#         regex=r"^update/(?P<pk>\d+)$",
#         view=views.ClubMemberUpdateView.as_view(),
#         name="update"
#     ),
#     url(
#         regex=r"^delete/(?P<pk>\d+)$",
#         view=views.ClubMemberDeleteView.as_view(),
#         name="delete"
#     ),
# ]

Team/urls.py
# clubs urls.py
from django.conf.urls import patterns, include, url
from . import views


# TODO: I want to standardize namespace names to all lowercase
# e.g. confirmAskJoin > confirmaskjoin,
#      editMember > editMember
# TODO: addMembers is plural. singularize it
# were we really going to add members en masse?


urlpatterns = [
    url(
        regex=r"^$",
        view=views.TeamListView.as_view(),
        name="list"
    ),
    url(
        regex=r"^new$",
        view=views.TeamCreateView.as_view(),
        name="new"
    ),
    url(
        regex=r"^(?P<pk>\d+)$",
        view=views.TeamDetailView.as_view(),
        name="detail"
    ),
    url(
        regex=r"^join/(?P<pk>\d+)$",
        view=views.TeamAskJoinView.as_view(),
        name="askjoin"
    ),
    url(
        regex=r"^confirm/(?P<pk>\d+)$",
        view=views.TeamConfirmAskJoinView.as_view(),
        name="confirmAskJoin"
    ),
    url(
        regex=r"^deleterequest/(?P<pk>\d+)$",
        view=views.DeletePlayerRequest, 
        name="deleterequest"
        ),
    url(
        regex=r"^deleteplayer/(?P<team>\d+)/(?P<player>\d+)$",
        view=views.DeleteTeamPlayer, 
        name="deleteplayer"
    ),

   url(
        regex=r"^addplayer/(?P<pk>\d+)$",
        view=views.TeamAddPlayerView.as_view(),
        name="addplayer"
    ),

    # url(
    #     regex=r"^removeplayer/(?P<pk>\d+)$",
    #     view=views.TeamRemovePlayerView.as_view(),
    #     name="removeplayer"
    # ),
   # url(
   #      regex=r"^editmember/(?P<pk>\d+)$",
   #      view=views.ClubEditMemberView.as_view(),
   #      name="editMember"
   #  ),
    url(
        regex=r"^results/(?P<pk>\d+)$",
        view=views.TeamResultsView.as_view(),
        name="result"
    ),
    # url(
    #     regex=r"^update/(?P<pk>\d+)$",
    #     view=views.ClubUpdateView.as_view(),
    #     name="update"
    # ),
    # url(
    #     regex=r"^delete/(?P<pk>\d+)$",
    #     view=views.ClubDeleteView.as_view(),
    #     name="delete"
    # ),
    # added by Daniel Henderson
    # call this url with the PK of a PlayerRequest object
    url(r'^compare/(?P<playerRequest>\d+)$', views.compareRequestedPlayers, name='compare'),
]

mysite/urls.py
from django.conf.urls import patterns, include, url

# from . import views
from login.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', welcome),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', logout_page),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
                       url(r'^register/$', register),
                       url(r'^register/success/$', register_success),
                       url(r'^home/$', home),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^player/', include('Players.urls', namespace='Players')),
                       url(r'^search/$', search),
                       url(r'^team/', include('Team.urls', namespace='Team')),
                       # url(r'^players/', include('clubMembers.urls', namespace='members')),
                       # url(r'^team/', include('Team.urls', namespace="Team")),
                       )
                       

Players/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.forms import ModelForm

# from nflstats.models import CsvModel

"""
This model will provide additional custom fields to the built-in
User class that django provided.

We need to store at least a phone number.
"""
class Player(models.Model):
    name = models.CharField(max_length = 100)
    pos = models.CharField(max_length = 5)
    fpts = models.FloatField()
    fptsg= models.FloatField()
    gp= models.FloatField()
    pyds = models.FloatField()
    ptd = models.FloatField()
    ryd = models.FloatField()
    rtd = models.FloatField()
    recyds = models.FloatField()
    rectd = models.FloatField()
    fum = models.FloatField()
    sack = models.FloatField()
    fr = models.FloatField()
    intercept = models.FloatField()
    td = models.FloatField()
    sfty = models.FloatField()
    fg = models.FloatField()
    fgmiss = models.FloatField()
    xpt = models.FloatField()

    # def __unicode__(self):
    #     return self.shortDescription









# class ClubMember(models.Model):
#     member = models.OneToOneField(User, primary_key=True)
#     # phone = models.CharField(max_length=12)
#     # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
#     phone_regex_us_easy = RegexValidator(regex=r'^\(\d{3}\)[ -]\d{3}[ -]\d{4}', message="Phone must be (###) 555 1212 or ### 555 1212; you can use dashes instead of spaces")
#     phone_number = models.CharField(max_length=20, validators=[phone_regex_us_easy], blank=False) # validators should be a list
#     zip_regex = RegexValidator(regex=r'^\d{5}$', message="5-digit Zip Code only")
#     member_zip = models.CharField(max_length=5, validators=[zip_regex], blank=False)
#     # we can add a photo or avatar image later
#     # TODO: what additional info about members do we want?

#     def create_member(self, phone_number, member, **extra_fields):
#         return self._create_member(phone_number, member, **extra_fields)

#     def requester_relationship(self, asking_member):
#         """
#         The asking_member will be the person him/herself,
#         or will be in the same club,
#         or will be in a club the person wants to join
#         or will be world+dog member.
#         Return a string of the relationship
#         :param asking_member:
#         :return:
#         """
#         if asking_member == self:
#             # the person himself
#             return "self_request"

#         ask_user = asking_member.member
#         self_user = self.member
#         asker_clubs = Club.objects.filter(members=ask_user)
#         self_clubs = Club.objects.filter(members=self_user)
#         common_clubs = asker_clubs & self_clubs
#         print("common clubs:")
#         for c in common_clubs:
#             print(c.name)
#         if len(common_clubs) > 0:
#             return "club_buddy"
#         # TODO: look up all club requests, get a queryset of those clubs
#         # compare to requester's clubs
#         # c_reqs = Club.objects.filter(members__requester=self_user)
#         # # club_requests = MemberRequest.objects.filter(requester=self_user)
#         #
#         # # requested_clubs = club_requests.all(self_clubs)
#         # common_clubs = asker_clubs & c_reqs
#         # print("request common clubs")
#         # for c in common_clubs:
#         #     print(c.name)
#         # if len(common_clubs) > 0:
#         #     return "prospective_club_buddy"
#         return "world_dog"

#     def get_prospective_buddy_info(self):
#         info = {"username":self.member.username}
#         return info







# class MemberRating(models.Model):
#     target_member = models.OneToOneField(User)
#     rated_by = models.ForeignKey(User, related_name="member_related", null=False, blank=False)
#     rating = models.PositiveSmallIntegerField()
#     rating_date = models.DateField()

Team/forms/player_form.py
from django.forms import ModelForm

from Team.models import Team, PlayerRequest

from django.http import Http404
import datetime




class newPlayerForm(ModelForm):
    class Meta:
        model = PlayerRequest
        fields = ["reasonMessage"]

    _requester = None
    _owner = None
    _teamToJoin = None
    _playerToJoin = None

    def set_requester(self, requester):
        self._requester = requester

    def set_owner(self, requester):
        self._owner = owner

    def set_teamToJoin(self, teamToJoin):
        self._teamToJoin = teamToJoin



    def save(self, *args, **kwargs):
        # if self._policy:
        #     self.instance.policies = self._policy
        # else:
        #     return Http404("something is wrong")

        # self.instance.request_date = datetime.datetime.now()
        self.instance.requester = self._requester
        # playerWanted = Player.objects.get(pk=)
        teamWanted = Team.objects.get(pk=self._teamToJoin)
        self.instance.teamToJoin = teamWanted
        # self.instance.clubToJoin = self._clubToJoin
        resp = super(newPlayerForm, self).save(*args, **kwargs)
        return resp

Players/views.py
from django.utils.translation import ugettext as _
from django.contrib import messages
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from braces.views import LoginRequiredMixin
from django.shortcuts import render_to_response
from django.template import RequestContext

# TSoD page 98, Class-based views
from django.core.urlresolvers import reverse
# end TSoD
from django.http import Http404, HttpResponseRedirect
# from clubs.models import Club
from django.contrib.auth.models import User
# from clubMembers.models import ClubMember

from .models import Player  #player class
# from thingys.forms.thingy_forms import new_thingy_form

from helpers.navbar_helpers import NavBarMixin

class PlayerActionMixin(object):
    fields = ('name', 'pos', 'fpts', 'fptsg', 'gp', 'pyds', 'ptd', 'ryd', 'rtd', 'recyds', 'rectd', 'fum', 'sack', 
        'fr', 'intercept', 'td', 'sfty', 'fg', 'fgmiss', 'xpt')

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super(PlayerActionMixin, self).form_valid(form)

    # def is_owner(self, thingy):
    #     if thingy.owner == self.request.user:
    #         return True
        return False


class PlayerDetailView(LoginRequiredMixin, PlayerActionMixin, NavBarMixin, DetailView):
    model = Player
    template_name = "Players/player_detail.html"
    page_title = _("Available Player Detail")

    def get(self, request, *args, **kwargs):
        player = self.get_object(queryset=None)
        # object_owner_member = ClubMember.objects.get(member=thingy.owner)
        # requesting_member = ClubMember.objects.get(member=request.user)
        # relationship = user_relation(thingy.owner, request.user)
        # print(relationship)
        # if relationship == "clubRelated":
        return super(PlayerDetailView, self).get(self, request, *args, **kwargs)
        # if relationship == "notRelated":
        #     print(" *******\nuser is trying to access non members thingys through url tweaking")
        #     print(request.user.username)
        #     print("is the user trying it\n *******")
        #     return HttpResponseRedirect(redirect_to=reverse('welcome'))


class PlayerSearchView(NavBarMixin, ListView):
    model = Player
    page_title = _("Thingy Search View")


# class PlayerDetailView(LoginRequiredMixin, ThingyActionMixin, NavBarMixin, DetailView):
#     model = Player
#     page_title = _("Your Thingys Detail")

#     def get_context_data(self, **kwargs):
#         context = super(PlayerDetailView, self).get_context_data(**kwargs)
#         this_Player = self.get_object()
#         # relationship = user_relation(this_thingy.owner, self.request.user)
#         # if relationship == "selfRelated":
#             # context["selfRelated"] = True
#         context["requested"], context["ask_object_lender"] = ask_borrow_object_for_owner(this_thingy, self.request.user)
#             # add more owner-specific info
#         # elif relationship == "clubRelated":
#             # context["clubRelated"] = True
#             # context["already_requested"], context["ask_objects"] = thingy_requested_by_user(this_thingy, self.request.user)
#             # context["request_accepted"] = thingy_request_accepted_for_user(this_thingy, self.request.user)
#             # context["available"] = thingy_available_for_request(this_thingy)
#             # add more club buddy specific info
#         # elif relationship == "pendingMemberMember":
#             # context["pendingMemberMember"] = True
#             # add more info for a pending member to view a current member thingy
#         # elif relationship == "memberPendingMember":
#             # context["memberPendingMember"] = True
#             # maybe a member wants to check out what kind of thingys
#             # a requesting member might have
#         # else:
#             # context["notRelated"] = True
#             # this person is not related to thingy owner in any way.
#             # give basic info
#         return context


# @staff_member_required
# def import(request):
#     if request.method == "POST":
#         form = DataInput(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             success = True
#             context = {"form": form, "success": success}
#             return render_to_response("imported.html", context,
#             context_instance=RequestContext(request))
#     else:
#         form = DataInput()        
#         context = {"form": form}
#         return render_to_response("imported.html", context,
#         context_instance=RequestContext(request)) 



# class ClubMemberMixin(object):
#     """
#     Only certain people are authorized to view, update ClubMember info.
#     The member who owns the info,
#     and a club leader who wants to allow them to join.
#     Maybe a simple view for other people in clubs they're in
#     """
#     def get_context_data(self, **kwargs):
#         context = super(ClubMemberMixin, self).get_context_data(**kwargs)
#         context["userInfo"] = User.objects.get(pk=self.kwargs["pk"])
#         return context




# class ClubMemberListView(LoginRequiredMixin, NavBarMixin, ListView):
#     """
#     This can be a stats page.
#     Maybe show how many members in each zip code or some basic member statistics.
#     Show graph of how many thingys per member, whatever. Something.
#     Not needed at this time, really.
#     No personal info, though.
#     """
#     model = ClubMember
#     page_title = _("Club Member List")


# class ClubMemberDetailView(LoginRequiredMixin, ClubMemberMixin, NavBarMixin, DetailView):
#     model = ClubMember
#     page_title = _("Club Member Detail")



# class ClubMemberUpdateView(LoginRequiredMixin, NavBarMixin, UpdateView):
#     model = ClubMember
#     page_title = _("Club Member Update View")


# class ClubMemberResultsView(LoginRequiredMixin, NavBarMixin,DetailView):
#     model = ClubMember
#     page_title = _("Club Member Results View")


# class ClubMemberDeleteView(LoginRequiredMixin, NavBarMixin, DeleteView):
#     model = ClubMember
#     page_title = _("Club Member Delete View")


# class ClubMemberInfoView(LoginRequiredMixin, ClubMemberMixin, NavBarMixin, DetailView):
#     """
#     This is to look at info about another member.
#     This view needs to find out the member relationship:
#       (Self)    self -> use DetailView
#       (Club)    in same club -> public + club-level info
#       (PndM)    in club that this pk wants to join -> public + club-prospective info
#       (ClbL)    club leader of club pk is in -> public + club-level info
#       (PndL)    club leader of club pk wants to join -> public + club-prospective + (whatever) info
#       (User)    world+dog -> public-level info only
#       (Anon)    anonymous user -> none
#     Since this view has a lot more checks, give it a different url,
#     since it'll take more processing to go through all the checks.
#     We can complete the (Self) and (PndL) first, and give everyone else -> none
#     """
#     model = ClubMember
#     page_title = _("Club Member Detail")


# class ClubMemberFirstTimeView(LoginRequiredMixin, ClubMemberMixin, NavBarMixin, DetailView):
#     """
#     A new member on the site will be sent here after registering.
#     They are automatically logged in, and this is the method called.
#     Put some ajax happy stuff in here, or a couple tutorial videos.
#     Tell them to complete their user profile and join or start a club.
#     """
#     model = ClubMember
#     page_title = _("Club Member First Time")

templates/Players/player_detail.html
{% extends "base.html" %}
        <!-- {% block title %}Welcome Back{% endblock %} -->
        <!-- {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %} -->
        {% block content %}
            <div class="col-md-2"></div>
            <div class="container col-md-4">
            <h3>Player Detail View</h3>
            <h5 style="color:darkorange"><b>Database Item: </b>{{ player.pk }}</h5>
            {# TODO: Delete Database Item key from template #}
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Name  &nbsp;</b> </td>
    <td <b>Pos  &nbsp;</b></td>
    <td <b>Fantasy Pts  &nbsp;</b></td>
    <td <b>Fantasy PPG  &nbsp;</b> </td>
    <td <b>Games Played  &nbsp;</b></td>
    <td <b>Pass Yds  &nbsp;</b> </td>
    <td <b>Pass TDs  &nbsp;</b> </td>
    <td <b>Rush Yds  &nbsp;</b> </td>
    <td <b>Rush TDs  &nbsp;</b> </td>
    <td <b>Rec Yds  &nbsp;</b> </td>
    <td <b>Rec TDs  &nbsp;</b> </td>
    <td <b>Fum Lost  &nbsp;</b> </td>
    <td <b>Sacks  &nbsp;</b> </td>
    <td <b>Fum Rec  &nbsp;</b> </td>
    <td <b>Ints  &nbsp;</b> </td>
    <td <b>Def TDs  &nbsp;</b> </td>
    <td <b>Safety  &nbsp;</b></td>
    <td <b>FG  &nbsp;</b> </td>
    <td <b>FG Miss  &nbsp;</b> </td>
    <td <b>Ex Pts  &nbsp;</b> </td>
  </tr>
  <tr>
    <td style="white-space:nowrap;">{{ player.name }} &nbsp;</td>
    <td>{{ player.pos }}</td>
    <td>{{ player.fpts }}</td>
    <td>{{ player.fptsg }}</td>
    <td>{{ player.gp }}</td>
    <td>{{ player.pyds }}</td>
    <td>{{ player.ptd }}</td>
    <td>{{ player.ryd }}</td>
    <td>{{ player.rtd }}</td>
    <td>{{ player.recyds }}</td>
    <td>{{ player.rectd }}</td>
    <td>{{ player.fum }}</td>
    <td>{{ player.sack }}</td>
    <td>{{ player.fr }}</td>
    <td>{{ player.intercept }}</td>
    <td>{{ player.td }}</td>
    <td>{{ player.sfty }}</td>
    <td>{{ player.fg }}</td>
    <td>{{ player.fgmiss }}</td>
    <td>{{ player.xpt }}</td>
  </tr>
</table> 
<br>
</br>
<div class="col-md-5"></div>

<!-- <div class="col-md-4"></div> -->
<!-- <div class="col-md-4"> -->
<center><a href="{% url 'Team:askjoin' player.pk %}" class="btn btn-lg btn-primary btn-block">Add to Queue</a></center>
</div>
<!-- <div class="col-md-4"></div> -->
{% endblock %}
        </div>
        <div class="col-md-4"></div>

templates/Players/player_list.html
<!-- {% extends "base_leftSidebar.html" %} -->
{% block content %}
    <!-- we are here -->
    {%  include "Players/player_list_partial.html" %}
{% endblock %}
<!-- {% block sidebar %}
    {% include "clubs/club_list_partial.html" %}
    <a href="{% url 'thingys:mynew' %}" class="btn btn-lg btn-default">Add a Thingy</a>
{% endblock %} -->

templates/Players/player_list_partial.html
{% extends "base.html" %}
{% block content %}

<!-- <div class="col-md-3"></div> -->
<div class="container col-md-4">
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Name  &nbsp;</b> </td>
    <td <b>Pos  &nbsp;</b></td>
    <td <b>Fantasy Pts  &nbsp;</b></td>
    <td <b>Fantasy PPG  &nbsp;</b> </td>
    <td <b>Games Played  &nbsp;</b></td>
    <td <b>Pass Yds  &nbsp;</b> </td>
    <td <b>Pass TDs  &nbsp;</b> </td>
    <td <b>Rush Yds  &nbsp;</b> </td>
    <td <b>Rush TDs  &nbsp;</b> </td>
    <td <b>Rec Yds  &nbsp;</b> </td>
    <td <b>Rec TDs  &nbsp;</b> </td>
    <td <b>Fum Lost  &nbsp;</b> </td>
    <td <b>Sacks  &nbsp;</b> </td>
    <td <b>Fum Rec  &nbsp;</b> </td>
    <td <b>Ints  &nbsp;</b> </td>
    <td <b>Def TDs  &nbsp;</b> </td>
    <td <b>Safety  &nbsp;</b></td>
    <td <b>FG  &nbsp;</b> </td>
    <td <b>FG Miss  &nbsp;</b> </td>
    <td <b>Ex Pts  &nbsp;</b> </td>
  </tr>
{%  for player in object_list %}
  <tr>
    <td> <a href="{% url 'Players:detail' player.pk %}" style="white-space:nowrap;">{{ player.name }} &nbsp; </a></td>
    <td>{{ player.pos }}</td>
    <td>{{ player.fpts }}</td>
    <td>{{ player.fptsg }}</td>
    <td>{{ player.gp }}</td>
    <td>{{ player.pyds }}</td>
    <td>{{ player.ptd }}</td>
    <td>{{ player.ryd }}</td>
    <td>{{ player.rtd }}</td>
    <td>{{ player.recyds }}</td>
    <td>{{ player.rectd }}</td>
    <td>{{ player.fum }}</td>
    <td>{{ player.sack }}</td>
    <td>{{ player.fr }}</td>
    <td>{{ player.intercept }}</td>
    <td>{{ player.td }}</td>
    <td>{{ player.sfty }}</td>
    <td>{{ player.fg }}</td>
    <td>{{ player.fgmiss }}</td>
    <td>{{ player.xpt }}</td>
  </tr>
{% endfor %}
</table> 
</div>
</div>

{% endblock %}